/**
 * Default Configuration
 *
 * Main configuration entry point that aggregates domain-specific configs.
 * Loads environment-specific overrides and validates the final configuration.
 *
 * DO NOT edit this file directly for configuration changes.
 * Instead, edit domain-specific files:
 * - config/service.ts - Service metadata
 * - config/database.ts - Database configuration
 * - config/api.ts - API Gateway configuration
 * - config/resources.ts - Resource naming
 * - config/features.ts - Feature toggles
 * - config/github.ts - GitHub/CI configuration
 * - config/aws.ts - AWS settings
 *
 * Or edit environment-specific files:
 * - config/local.ts (future)
 * - config/localstack.ts
 * - config/staging.ts
 * - config/production.ts
 *
 * @module config/default
 */

import localstackConfig from "./localstack";
import stagingConfig from "./staging";
import productionConfig from "./production";
import { databaseConfig } from "./database";
import { apiConfig } from "./api";
import { serviceConfig } from "./service";
import { resourcesConfig } from "./resources";
import { featuresConfig } from "./features";
import { createGitHubConfig } from "./github";
import { createAwsConfig } from "./aws";
import { ConfigSchema } from "./schema";
import type { IConfig } from "./types";

// Re-export types for convenience
export type { IConfig } from "./types";

/**
 * Get AWS account ID from environment variables
 *
 * @param envName - Environment name (local, dev, staging, production)
 * @returns AWS account ID
 */
function getAccountId(envName: string): string {
  const accountId =
    process.env.AWS_ACCOUNT_ID || process.env.CDK_DEFAULT_ACCOUNT;

  if (accountId) {
    return accountId;
  }

  if (envName === "local") {
    return "000000000000";
  }

  throw new Error(
    "AWS account ID is required. Set AWS_ACCOUNT_ID (or CDK_DEFAULT_ACCOUNT) environment variable."
  );
}

/**
 * Get AWS region from environment variables
 *
 * @param envName - Environment name (local, dev, staging, production)
 * @returns AWS region
 */
function getRegion(envName: string): string {
  const region =
    process.env.AWS_REGION ||
    process.env.AWS_DEFAULT_REGION ||
    process.env.CDK_DEFAULT_REGION;

  if (region) {
    return region;
  }

  if (envName === "local") {
    return "us-east-1";
  }

  throw new Error(
    "AWS region is required. Set AWS_REGION (or AWS_DEFAULT_REGION / CDK_DEFAULT_REGION) environment variable."
  );
}

/**
 * Create default configuration from domain-specific configs
 *
 * @param envName - Environment name (local, dev, staging, production)
 * @returns Default configuration
 */
function createDefaultConfig(envName: string): IConfig {
  const github = createGitHubConfig(envName);
  const aws = createAwsConfig(envName);

  return {
    envName,
    accountId: getAccountId(envName),
    region: getRegion(envName),

    // Domain-specific configurations
    service: serviceConfig,
    database: databaseConfig,
    api: apiConfig,
    resources: resourcesConfig,

    // Optional configurations
    github,
    aws,
    features: featuresConfig,

    // Legacy properties for backward compatibility
    gitHubRepo: github?.repo,
    gitHubBranch: github?.branch,
    codestarConnectionId: github?.codestarConnectionId,
    parameterStorePrefix: process.env.APP_BASE_PATH || undefined,
  };
}

/**
 * Load environment-specific configuration
 * Supports: local, localstack, staging, production
 * Validates that required properties (account, region) are present
 */
function loadConfig(): IConfig {
  const envName = process.env.ENV_NAME || "local";

  let config: IConfig;

  try {
    // Create default config
    const defaultConfig = createDefaultConfig(envName);

    // Load environment-specific overrides
    switch (envName) {
      case "localstack":
        config = { ...defaultConfig, ...localstackConfig };
        break;

      case "staging":
        config = { ...defaultConfig, ...stagingConfig };
        break;

      case "production":
        config = { ...defaultConfig, ...productionConfig };
        break;

      default:
        config = defaultConfig;
    }
  } catch (error) {
    console.warn(
      `Failed to load config for environment '${envName}', using default:`,
      error
    );
    config = createDefaultConfig(envName);
  }

  // Validate required properties for Three-Flow architecture
  if (!config.accountId) {
    throw new Error(
      `AWS account ID is required for environment '${envName}'. Set AWS_ACCOUNT_ID environment variable.`
    );
  }

  if (!config.region) {
    throw new Error(
      `AWS region is required for environment '${envName}'. Set AWS_REGION environment variable.`
    );
  }

  // Zod validation for clearer, typed errors
  const result = ConfigSchema.safeParse(config);
  if (!result.success) {
    const formatted = result.error.issues
      .map((i) => `${i.path.join(".")}: ${i.message}`)
      .join("\n");
    throw new Error(
      `Invalid configuration for env '${envName}':\n${formatted}`
    );
  }
  return result.data;
}

export default loadConfig();
